site_name: Big Data System Design
site_author: Kushal Luthra
site_description: Big Data Architecture & principles

repo_name: big-data-architecture
repo_url: https://github.com/kushal-luthra/big-data-architecture
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2022 Kushal Luthra

theme:
  name: material
  language: en

nav:
  - Home: index.md
  - Big data architectural Patterns:
      - Introduction : Big-data-architectural-patterns/Big-data-architectural-patterns-1.md
      - Big Data Architectural Principles : Big-data-architectural-patterns/Big-data-architectural-patterns-2.md
      - Collect Layer : Big-data-architectural-patterns/Big-data-architectural-patterns-3.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kushal-luthra
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kushal_luthra
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kushalluthra/
