site_name: Big Data Architecture Patterns
site_author: Kushal Luthra
site_description: Big Data Architecture & principles

repo_name: big-data-architecture
repo_url: https://github.com/kushal-luthra/big-data-architecture
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2022 Kushal Luthra

theme:
  name: material
  language: en

nav:
  - Home: index.md
  - Big data Architectural Patterns:
      - Introduction : Big-data-architectural-patterns/Big-data-architectural-patterns-1.md
      - Big Data Architectural Principles : Big-data-architectural-patterns/Big-data-architectural-patterns-2.md
      - Data Collection Layer : Big-data-architectural-patterns/Big-data-architectural-patterns-3.md
      - Data Processing Layer : Big-data-architectural-patterns/Big-data-architectural-patterns-4.md
      - Data Consumption Layer : Big-data-architectural-patterns/Big-data-architectural-patterns-5.md
      - Putting it all together : Big-data-architectural-patterns/Big-data-architectural-patterns-6.md
      - Design Patterns : Big-data-architectural-patterns/Big-data-architectural-patterns-7.md
  - Storage Layer:
      - Row-based Vs Column-based File Formats : Storage Layer Choices/row based and column based file formats.md
      - Text-based File Formats : Storage Layer Choices/Text File Formats.md
      - Big Data File Formats : Storage Layer Choices/big data file formats.md
      - File Compression Techniques in Big Data Systems :  Storage Layer Choices/File Compression techniques in Big Data.md
  - HBase :
    - Why HBase : HBase/1-HBase.md
    - HBase Properties : HBase/2-HBase.md
    - HBase Components : HBase/3-HBase.md
    - HBase Architecture - Part 1 : HBase/4-HBase.md

  - Case Study:
    - IHS Markit System Design Case Study (2020): case study/IHS-Markit-System-Design.md
    - ZS Associates Data Consultant System Design Case Study (2020):  case study/ZS-Associates-Data-Consultant-Case-Study.md
    - Interview Questions : case study/Sample-Questions-System-Design.md
  - About Me: aboutme.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kushal-luthra
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kushal_luthra
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kushalluthra/
